### ISSUE TITLE
Host/Path Validation

### ISSUE THREAD

**Issue by jbowen93** [30x/enrober#105]
During a createDeployment when the user supplies the paths option. Enrober should be doing validation on the three parameters of each path.

This will save us some headaches in the future if they input an invalid path and we end up digging through k8s to find the issue. Let's fail fast.

Host validation shouldn't be necessary since we are getting them from apigee not the user. Though maybe.

**Comment by jbowen93** [comment]
For now path validation will be implemented with a regex preventing query parameters. I'm going to assume that hosts provided by Edge are valid.

Regex can be seen here: https://regex101.com/r/qv3qJ0/1

**Comment by AdamMagaluk** [comment]
You can also use this function that was pulled from k8s-router. https://github.com/30x/dispatcher/blob/master/router/pods.go#L374-L385

**Comment by jbowen93** [comment]
@whitlockjc There was discussion around this. Did we settle on a final regex solution that we liked?

**Comment by AdamMagaluk** [comment]
This is what I had documented from the discussion: `[A-Za-z0-9\-._~!$&'()*+,;=:@]+|%[0-9A-Fa-f]{2}`

**Comment by jbowen93** [comment]
That's what I have as well. We'll need to modify the function that uses it though as it's possible to have a string that gets several matches but is still invalid. An example string would be `%20testing%a`.

Here's a playground of this: https://play.golang.org/p/hdgy3K_-I7
