### ISSUE TITLE
Call out's to internal APIs need to provide valid header for security.

### ISSUE THREAD

**Issue by jbowen93** [30x/enrober#11]
In deployment API, it would need to call build (shipyard) api to download PTS which will hit private path hence need for private api key.

**Comment by prabhatjha** [comment]
It will be the apiKey for Apigee namespace

**Comment by jbowen93** [comment]
Should mount the `routing` secret to the `enrober` pod and access the `private-api-key` value as an env var.

**Comment by jbowen93** [comment]
Relies on [#9](https://github.com/30x/enrober/issues/9)

**Comment by prabhatjha** [comment]
Not needed for alpha .
