### ISSUE TITLE
update bug - minikube

### ISSUE THREAD

**Issue by noahdietz** [30x/enrober#119]
the docker registry url of `localhost:5000` causes incorrect split on deployment image update.

so image name = `localhost:5000/acme/example:1` splits into `localhost` and concats with a new revision to be `localhost:2`.

I think this is the spot:
https://github.com/30x/enrober/blob/staging/pkg/server/handlers.go#L365

**Comment by jbowen93** [comment]
Issue it actually at https://github.com/30x/enrober/blob/staging/pkg/server/handlers.go#L377
