### ISSUE TITLE
Environment creation must generate a secret and store it in Apigee's KVM

### ISSUE THREAD

**Issue by jbowen93** [30x/enrober#22]
Environment/namespace creation API would generate a random secret and store it as kube secret for given `namespace` AND make an Edge MGMT server API call to add an entry in org's KVM where key is `namespace` name and value is random secret.

**Comment by mpnally** [comment]
See https://docs.google.com/a/apigee.com/document/d/1zupDMK2OuKg3O3109Essqe_3AU8qS1ic2XdAJkza06k/edit?usp=sharing where a slightly different model is described.

**Comment by prabhatjha** [comment]
Thanks @mpnally . For folks who don't have access to doc, namespace creation API would return the `key and secret` which then Apigee user have to store in KVM using Apigee MGMT API. This avoids direct dependency on Edge to Enrober .

**Comment by jbowen93** [comment]
Modifications that need to take place:

- When a `POST` call to enrober's environment endpoint is made enrober should auto generate a secret for public/private routing as opposed to taking a user given secret. The caller decides if they want a secret for public routing, private routing or both. 
- The secret(s) should be stored in the kubernetes namespace and passed back to the client in a documented format so that the client can make a `POST` call to the the Apigee KVM endpoint:  `https://api.enterprise.apigee.com/v1/organizations/{org-name}/keyvaluemaps`

Example call body:

```
{   
 "name" : "kubernetes-env1",
 "entry" : [ 
  {
   "name" : "public-api-key",
   "value" : "super-secret-public-key"
  },
  {
   "name" : "private-api-key",
   "value" : "super-secret-private-key"
  } 
 ]
}
```

- Must also support the flow where the environment/secret already exists and must be modified through a `PATCH` call to enrober's environment endpoint.

**Comment by mpnally** [comment]
I'm struggling to understand the intent of your proposed JSON. What is "entry"? Why are "public-api-key" and "private-api-key" expressed as JSON values instead of JSON names? Would this work:
```json
{   
 "isA": "Environment",
 "name" : "kubernetes-env1",
 "public-api-key" : "super-secret-public-key",
 "private-api-key" : "super-secret-private-key"
}
```

**Comment by jbowen93** [comment]
For clarity the above example call would be made to the apigee kvm api. See [here](http://docs.apigee.com/management/apis/post/organizations/%7Borg_name%7D/keyvaluemaps).
