### ISSUE TITLE
Lock down PTS for Shipyard

### ISSUE THREAD

**Issue by whitlockjc** [30x/enrober#36]
For the Shipyard use case _(Node.js on Apigee Edge)_ we want to lock down the PTS such that you can only call enrober with a PTS that was created using the images API in `30x/shipyard`.  Not only that but we need to make sure that the namespace a caller is associated with can only deploy a PTS that is associated with a host in that namespace.

As @mpnally puts it:

    Basically want to restrict it so that Enrober only deploys PTS from Todd's tool.
    One easy way to check is to say that enrober will only deploy Pod Template
    Specs whose URL has a hostname that is the same as the hostname of the
    request that Enrober is processing. This means that it is a URL that points to
    either Enrober itself, or the build service running in the same namespace.

**Comment by jbowen93** [comment]
I understand the goal here. I'm slightly unclear on Martin's comment where we are looking for a `hostName` of the PTS. Is this referring to the `publicHosts/privateHosts` annotation on the PTS? I'm not immediately aware of how `enrober` would know what it's own annotations would be at runtime.

**Comment by mpnally** [comment]
I was thinking of something simpler. Assuming that our software is at `https://shipyard.e2e.apigee.net`, my suggestion is that enrober should check that the URL of the PTS is also at `https://shipyard.e2e.apigee.net`. The value `https://shipyard.e2e.apigee.net` is in the Host header of the incoming request. This does not guarantee that Nike cannot use Coke's PTS, but if they try, it will fail when they try to load the Coke image. (We can also easily cause it to fail on the PTS access too—you would only have to forward the incoming JWT to Todd for him to check).

**Comment by jbowen93** [comment]
I'm actually going to reopen this as it wasn't implemented in Shipyard Alpha-1 or whatever our naming is. If it's needed/desired I can fix it and deploy with no downtime to e2e and prod. I think this may be worth discussing more formally as a part of a Alpha v2 desired API implementation.

**Comment by jbowen93** [comment]
Need to do testing on E2E

**Comment by jbowen93** [comment]
Testing on E2E works. Merging PR.
