### ISSUE TITLE
'201 Created' responses are missing the Location header

### ISSUE THREAD

**Issue by mpnally** [30x/enrober#37]
Returning the URL of the newly-created resource in the Location header of the '201 Created' response is a fundamental part of the HTTP protocol that Apigee should get right. See https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.2.2 — "The newly created resource can be referenced by the URI(s) returned in the entity of the response, with the most specific URI for the resource given by a Location header field. "

Note that [it is OK to return a relative URL](https://tools.ietf.org/html/rfc7231#section-7.1.2), although an absolute URL is more client-friendly, IMO

**Comment by jbowen93** [comment]
For a POST on `localhost:9000/beeswax/deploy/api/v1/environmentGroups/group1/environments` is a `Location` header of `/beeswax/deploy/api/v1/environmentGroups/group1/environments/{env-name}` fine?
