### ISSUE TITLE
add or update API

### ISSUE THREAD

**Issue by prabhatjha** [30x/enrober#4]
- [x]  Add and update secret to namespace
- [x]  In the deploy service, this secret will be specified on POST. It can also be specified on PATCH

**Comment by jbowen93** [comment]
> Comment moved from issue #11 in k8s-pods-ingress

It's up to the caller to create, retain, and pass the key at runtime. We don't want to get into the business of secret storage. Storing it in the namespace is the only persistence we want. To be clear we need to make the following changes.
