### ISSUE TITLE
Environment creation must take a list of valid hostnames

### ISSUE THREAD

**Issue by jbowen93** [30x/enrober#5]
When creating an environment we must take an array or strings that contains a list of valid hostnames. Deployments running within this environment must ensure that they only receive traffic from these white listed hostnames.

**Comment by prabhatjha** [comment]
It should do simple validation through regex and also verify that given hostname is not already claimed by other namespaces.

**Comment by jbowen93** [comment]
The data model for this is going to cause checks to be extremely inefficient at scale.

**Comment by whitlockjc** [comment]
We are already validating this in the ingress but if @jbowen93 wanted to do it in enrober, we could bubble out the reusable code from here into a utility/common package: https://github.com/30x/k8s-pods-ingress/blob/master/ingress/pods.go#L103

**Comment by mpnally** [comment]
I think it's important to verify it in both places. We need to verify it in
the ingress, because that is the place that gives a cast-iron guarantee of
enforcement. We want to implement it in the deployment tool to give early
feedback to users. Users don't want to wait until the ingress throws it out
to find out they made a mistake.

Martin

**Comment by whitlockjc** [comment]
I agree.  We're getting to the point where the different 30x projects are starting to share needs _(k8s client creation, hostname/ip validation, ...)_.  We should create some shared projects to house of these things.

**Comment by jbowen93** [comment]
My concern is that the process we have to do is, for every `hostname` that we want to allow on a newly created namespace we have to get a list of all existing namespaces and then loop through all of their allowed `hostnames`. If there is a match then we reject the new namespace. This is going to end up being extremely inefficient for a high number of namespaces and/or hostnames.

**Comment by mpnally** [comment]
Isn't there a way to use etcd query for this?

Martin

**Comment by jbowen93** [comment]
Since there's only one I/O call to make to the kubernetes backend it doesn't look like this is actually going to be a bottleneck. I've tested it with creating 10 namespaces and there's no significant increase in time. I'll put a note to come back to this if it poses an issue later.

**Comment by jbowen93** [comment]
First pass is done, need to add unit testing.

**Comment by jbowen93** [comment]
PR created, see [#21](https://github.com/30x/enrober/pull/21)
