### ISSUE TITLE
Integrate with Apigee KVM

### ISSUE THREAD

**Issue by whitlockjc** [30x/enrober#58]
For Apigee to support the simplified Edge proxy wiring, we need `enrober` to put the public routing secret into the KVM upon environment creation and update the KVM whenever the API to update the secret is called, if one exists.

**Comment by whitlockjc** [comment]
http://docs.apigee.com/api-services/content/environment-keyvalue-maps

**Comment by jbowen93** [comment]
Clarifying Jeremy's first comment. There is currently no way to update environment secrets, it was deemed as unnecessary. Currently a PATCH on an environment can only modify the hostNames array.

**Comment by whitlockjc** [comment]
So in that case, we just need to put the key into the KVM when we create a new environment.

**Comment by jbowen93** [comment]
That is what I'm currently implementing. Just making a post call per [this](http://docs.apigee.com/management/apis/post/organizations/%7Borg_name%7D/environments/%7Benv_name%7D/keyvaluemaps) documentation.

**Comment by jbowen93** [comment]
Currently I'm mirroring the k8s secret store by naming the KVM map `routing` and the name of the entry will be `public-key`.
