### ISSUE TITLE
Add endpoints to manage secrets

### ISSUE THREAD

**Issue by jbowen93** [30x/enrober#76]
Need to be able to create/update secrets separate from environment creation.

Endpoints should be `/environments/{org}:{env}/secret` and `/environments/{org}:{env}/config`

**Comment by mpnally** [comment]
Can we do a design for this? What will the API look like?

**Comment by jbowen93** [comment]
@mpnally I've coded up and implemented the endpoint. 

The paths are as follows:

`GET` and `POST` on `/environments/{org}:{env}/config`
`GET`, `PATCH`, `DELETE` on `/environments/{org}:{env}/config/{map}`

**Comment by mpnally** [comment]
What is a config? (Also, what is an endpoint? Isn't that a SOAP/WSDL term?)

**Comment by whitlockjc** [comment]
These endpoints were the ones we agreed upon implementing to manage environment configuration.  It's basically a key/value map that we'll setup per environment that the application author can reference in their PTS.

**Comment by mpnally** [comment]
I'd still like to understand what a "config" is. Is there a definition written down?

**Comment by jbowen93** [comment]
http://kubernetes.io/docs/user-guide/configmap/ 

As for what the user sees it is a named KV map. The user Posts JSON of the form:
```
{
  "configName": "testName",
  "vars": {
    "testKey1": "testVal1",
    "testKey2": "testVal2"
  }
}
```

I'm in the process of reworking the README as it's out of date.

**Comment by whitlockjc** [comment]
This was your design, it's a key/value map for storing information in Kubernetes that will eventually be backed by the KVM.

**Comment by mpnally** [comment]
So a "config" and a map are the same thing? That is confusing.

**Comment by whitlockjc** [comment]
Oh, so it's the URI pattern that is confusing.  Gotcha.

**Comment by mpnally** [comment]
The design I thought we agreed to is that secrets would be stored in an Edge KVM map associated with the environment. That KVM map would be synchronized with a K8S ConfigMap by a congress-style daemon. The K8S ConfigMap would not be visible in any way to the user. There is no Enrober "endpoint" for maps required in this design. We talked about this orally — was it ever written down?

**Comment by jbowen93** [comment]
I recall that conversation but I was under the impression that we were going to do that implementation at a later time and this was going to be our intermediary solution.

**Comment by whitlockjc** [comment]
Yes, we agreed the backing would be secrets.  But we also agreed that to the user, it is just an environment configuration.  So what is being used behind the scenes doesn't matter right now.  Right?

**Comment by mpnally** [comment]
I think we should only do the Edge KVM solution. An intermediate solution just weakens the integration of Shipyard with Edge.

**Comment by mpnally** [comment]
@whitlockjc Yes, it doesn't matter what is under the covers, but enrober "endpoints" are not under the covers. I expect the user experience would be to set the values through Edge (http://docs.apigee.com/api-services/content/environment-keyvalue-maps). The rest can be "under the covers".

**Comment by mpnally** [comment]
We really should have written down a design for this and debated it with Mukunda and Nanden before we implemented. This is an important part of the user experience.
