### ISSUE TITLE
Remove ability to pass PTS Directly

### ISSUE THREAD

**Issue by jbowen93** [30x/enrober#79]
Moving forward we will only support passing PTS through a PTS_URL.

**Comment by whitlockjc** [comment]
Did we agree upon this?  I thought being able to pass a full PTS was our _out_ for when our abstraction is lacking anything.  @mpnally, what are your thoughts?

**Comment by mpnally** [comment]
The upside of allowing a PTS is the one you give. The downside is that there is no persistent record of what was done - it violates the model where every code change should be persistently recorded, in some repository. I like the idea of removing the ability to provide a PTS until we prove its really necessary.

**Comment by jbowen93** [comment]
I believe this is a fitting change as we move `enrober` from a more general deployment model to be tied more towards the Apigee specific use cases. As we would like there to be a persistent backing for all PTS this removes the ability for there to be inconsistencies. Additionally, I don't believe any user has actually utilized this functionality.
