### ISSUE TITLE
Add support for environment configuration

### ISSUE THREAD

**Issue by whitlockjc** [30x/enrober#81]
For Shipyard application/environment configuration, we will consuming Apigee's KVM.  As a Shipyard user, to store your application/environment configuration you will create a specially-named _(`shipyard`)_ map in the _environment-scoped_ Apigee KVM for your environment.  `enrober` will need to be updated to support as described below.

To allow this, `enrober` will need to be updated to allow environment variable references to be used at deployment create/update time.  We will use a syntax similar to Kubernetes' `ConfigMap` and `Secret` objects.  Below is an example:

```yaml
env:
  - name: DATABASE_URL
    valueFrom:
      kvmKeyRef:
        key: db-url
```

We use `kvmKeyRef` to indicate that this is a KVM map reference, much like `configMapKeyRef` and `secretKeyRef` are used for `ConfigMap` and `Secret` references respectively.  Where our implementation differs is the `name` attribute.  For Shipyard's first release, application/environment configuration will be stored in a singular, specially-named map called `shipyard`.  So specifying a map name does not make sense _(yet)_.

**Note:** I'm on the fence about this one.  I could also see an initial implementation where we do support `name` but default its value to `shipyard` when not provided.  `shipyardctl` would be updated to only support `shipyard` and so only power users would be able to use this _(if they figured out how to use this undocumented feature)_.

Once a create/update deployment request is made, `enrober` will query the appropriate KVM map for the Apigee environment and will pull down the referenced KVM values and use those for as the value portion of an environment variable literal.  So based on the example above, if the `database-url` key had a value of `postgres://localhost:5432/todo` in the `shipyard` map, the environment variable literal used to create the Kubernetes deployment would look like this:

```yaml
env:
  - name: DATABASE_URL
    value: postgres://localhost:5432/todo
```

**Comment by mpnally** [comment]
Could the map just be called 'environment_variables' or somesuch rather than 'shipyard'?

**Comment by whitlockjc** [comment]
Please hold off on comments, design doc incoming tomorrow.

**Comment by whitlockjc** [comment]
I have updated the issue description with a summarization of the agreed-upon design document.  Please use the design document to fill in any gaps in the description or reach out if there is more clarity needed.
