### ISSUE TITLE
Synchronize environment with Apigee

### ISSUE THREAD

**Issue by whitlockjc** [30x/enrober#88]
As Shipyard becomes better integrated with Apigee, we need to keep data synchronized between Apigee and Kubernetes.  Where important, like the hostnames of Apigee environments being synchronized to Shipyard environments, we need a way to force this synchronization any time things might have become out of sync.

**Note:** This will eventually be handled by infrastructure currently being developed.  This is a short-term solution that is not ideal, as in it's not automatically handled for the user, but it does help fix the situation.

**Comment by AdamMagaluk** [comment]
I'd propose to create another http resource called. `POST /environments/{org}:{env}/sync` The resource would hit the Apigee management api and gather the host information and any other needed info. It would use the Authorization header from the original client request to authenticate with Apigee.

**Comment by jbowen93** [comment]
I agree that a sync endpoint is the easiest way to implement this. @AdamMagaluk I can take this after I finish my current issue #86 which involves a bit of refactoring.

**Comment by whitlockjc** [comment]
Why not just make this part of the `PATCH` process?  Updating an environment to sync it's Apigee Edge data seems like a decent idea.  Thoughts?

**Comment by jbowen93** [comment]
Well we don't support a `PATCH` on environments anymore.

**Comment by whitlockjc** [comment]
But maybe this is a good reason?  I don't mind either way.

@mpnally?

**Comment by AdamMagaluk** [comment]
I'm fine with either approach the logic will be the same.  I chose a separate resource because i know we talked about removing some of the environments resources because they are no longer going to be managed by the user.

**Comment by jbowen93** [comment]
@AdamMagaluk Was this resolved with #92?
