### ISSUE TITLE
When a deployment is created the pod template spec should include lines that make the public and private API secrets available to the containers as environment variables

### ISSUE THREAD

**Issue by jbowen93** [30x/enrober#9]

**Comment by jbowen93** [comment]
Relies on [#8](https://github.com/30x/enrober/issues/8)

**Comment by prabhatjha** [comment]
This needs to be assessed so that we have clarify for delivery for alpha.

**Comment by tnine** [comment]
@jbowen93 I agree with this, however we must have a standard mechanism for how we create secrets.  Do you have any example documentation that outlines the secret format so I can generate the default template spec?

**Comment by jbowen93** [comment]
I'll create a new branch under 30x/enrober for alpha release and I'll update the documentation on how secrets are created and stored. For a quick reference secrets are stored as a key-value pairs and for our uses in environments the returned JSON format is: 
```
{
    "private-api-key": {256-bit base64 encoded string},
    "public-api-key": {256-bit base64 encoded string}
}
```
The name of the secret in kubernetes is `routing` and its two fields are `private-api-key` and `public-api-key`.
